name: Java CI
on:
  push:
    branches:
      - '[4-9]+.[0-9]+.x'
      - '[3-9]+.[3-9]+.x'
  pull_request:
    branches:
      - '[4-9]+.[0-9]+.x'
      - '[3-9]+.[3-9]+.x'
  workflow_dispatch:
    inputs:
      message:
        description: 'Snapshot information (e.g. New Core Snapshot Tue Dec 15 00:07:18 UTC 2020 f212f54)'
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['11', '14', '17']
    env:
      RUN_TESTS_ONLY: false
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - name: Print Dispatch Information
        if: github.event_name == 'workflow_dispatch'
        env:
          DISPATCH_INFORMATION: ${{ github.event.inputs.message }}
        run: echo $DISPATCH_INFORMATION
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}
      - name: Run Build
        id: build
        uses: gradle/gradle-build-action@v3
        env:
          GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
        with:
          arguments: build -Dgeb.env=chromeHeadless
